#.travis.yml
language: java

dist: trusty

jdk:
  - oraclejdk8
  - openjdk7

before_install:
  - echo "Downloading Maven 3.2.5" 
   && wget https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip 
   && unzip -qq apache-maven-3.2.5-bin.zip 
   && export M2_HOME=$PWD/apache-maven-3.2.5 
   && export PATH=$M2_HOME/bin:$PATH
   && cp ./tools/ci/.travis.settings.xml $HOME/.m2/settings.xml
   && mvn -version

install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -U -e
  - sh ./check_format.sh
    
script:
  - mvn test cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)